name: ie-bank-frontend

on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build -- --mode development --dest dist-dev

      - name: npm install, build, and test 
        run: |
          npm install
          npm run build -- --mode uat --dest dist-uat
      
      - name: Upload artifact for development
        uses: actions/upload-artifact@v4
        with:
          name: node-app-dev
          path: dist-dev/

      - name: Upload artifact for UAT
        uses: actions/upload-artifact@v4
        with:
          name: node-app-uat
          path: dist-uat/

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app-dev

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Fetching SWA token from Key Vault'
        id: fetch-swaDev-token
        run: |
          DEV_SWA_TOKEN=$(az keyvault secret show --vault-name BestBank-KV-dev --name SWAtoken --query value -o tsv) \
          && echo "DEV_SWA_TOKEN=${DEV_SWA_TOKEN}" >> $GITHUB_ENV

      - name: List files in the workspace
        run: ls -R
      
      - name: 'Deploy to Azure Static Web App'
        id: deploy-to-staticwebapp
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.DEV_SWA_TOKEN }}
          app_location: .
          output_location: dist-dev

  deploy-uat:
    if:  (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main') || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'UAT'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app-uat

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Fetching SWA token from Key Vault'
        id: fetch-swaUat-token
        run: |
          UAT_SWA_TOKEN=$(az keyvault secret show --vault-name BestBank-KV-uat --name SWAtoken --query value -o tsv) \
          && echo "UAT_SWA_TOKEN=${UAT_SWA_TOKEN}" >> $GITHUB_ENV

      - name: List files in the workspace
        run: ls -R
      
      - name: 'Deploy to Azure Static Web App'
        id: deploy-to-staticwebapp
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.UAT_SWA_TOKEN }}
          app_location: .
          output_location: dist-uat