name: ie-bank-frontend

on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  FRONTEND_WEBAPP_DEV: bestbank-fe-dev
  FRONTEND_WEBAPP_UAT: bestbank-fe-uat
  FRONTEND_WEBAPP_PROD: bestbank-fe-prod
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: npm install, build, and test (Development)
        run: |
          npm install
          npm run build -- --mode development --dest dist-dev

      - name: npm install, build, and test (UAT)
        run: |
          npm install

          npm run build -- --mode uat --dest dist-uat

      - name: npm install, build, and test (Production)
        run: |
          npm install

          npm run build -- --mode production --dest dist-prod

      - name: Upload artifact for Development
        uses: actions/upload-artifact@v4
        with:
          name: node-app-dev
          path: dist-dev/

      - name: Upload artifact for UAT
        uses: actions/upload-artifact@v4
        with:
          name: node-app-uat
          path: dist-uat/
          
      - name: Upload artifact for prod
        uses: actions/upload-artifact@v4
        with:
          name: node-app-prod
          path: dist-prod/

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app-dev

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Fetch SWA token from Key Vault (Development)
        id: fetch-swaDev-token
        run: |
          DEV_SWA_TOKEN=$(az keyvault secret show --vault-name BestBank-KV-dev --name SWAtoken --query value -o tsv) \
          && echo "DEV_SWA_TOKEN=${DEV_SWA_TOKEN}" >> $GITHUB_ENV

      - name: List files in the workspace (Development)
        run: ls -R

      - name: Deploy to Azure Static Web App (Development)
        id: deploy-to-staticwebapp
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.DEV_SWA_TOKEN }}
          action: "upload"
          app_location: .
          output_location: dist-dev

  deploy-uat:
    if: (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main') || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build, deploy-dev]
    environment:
      name: 'UAT'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app-uat

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Fetch SWA token from Key Vault (UAT)
        id: fetch-swaUat-token
        run: |
          UAT_SWA_TOKEN=$(az keyvault secret show --vault-name BestBank-KV-uat --name SWAtoken --query value -o tsv) \
          && echo "UAT_SWA_TOKEN=${UAT_SWA_TOKEN}" >> $GITHUB_ENV

      - name: List files in the workspace (UAT)
        run: ls -R

      - name: Deploy to Azure Static Web App (UAT)
        id: deploy-to-staticwebapp
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.UAT_SWA_TOKEN }}
          action: "upload"
          app_location: .
          output_location: dist-uat

  deploy-prod:
    if: (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main') || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build, deploy-dev, deploy-uat]
    environment:
      name: 'production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app-prod

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Fetch SWA token from Key Vault (prod)
        id: fetch-swa-prod-token
        run: |
          PROD_SWA_TOKEN=$(az keyvault secret show --vault-name BestBank-KV-prod --name SWAtoken --query value -o tsv) \
          && echo "PROD_SWA_TOKEN=${PROD_SWA_TOKEN}" >> $GITHUB_ENV

      - name: List files in the workspace (prod)
        run: ls -R

      - name: Deploy to Azure Static Web App (prod)
        id: deploy-to-staticwebapp
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.PROD_SWA_TOKEN }}
          action: "upload"
          app_location: .
          output_location: dist-prod
